# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7533ea78b7bd634f84ff4f63c28fe481c97792128f8dee26373e8f4ea9f8d3ae83f13fc621fe988c26ff1f77cde89202ac3d01d83d162aabab0228366bb0f7e

test:
  secret_key_base: b84f80952a87f8f459bc7f36112a93af2e110dd7168bab95cdca219dba1e587da77161e5b6fed624d2f4610e3806d9d46658d8cf2ecb45fb2f1a5563e745dd22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
